<?php
return [
	"PUSHER_APP_ID" => env("PUSHER_APP_ID"),
	"PUSHER_APP_KEY" => env("PUSHER_APP_KEY"),
	"PUSHER_APP_SECRET" => env("PUSHER_APP_SECRET"),
	"PUSHER_HOST" => env("PUSHER_HOST"),
	"PUSHER_PORT" => env("PUSHER_PORT"),
	"PUSHER_SCHEME" => env("PUSHER_SCHEME"),
	"PUSHER_APP_CLUSTER" => env("PUSHER_APP_CLUSTER"),
];


